---
name: Version Bump

on:
  workflow_dispatch:
    inputs:
      version_number_override:
        description: "New version override (leave blank for automatic calculation, example: '2024.1.0')"
        required: false
        type: string

jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.set-final-version-output.outputs.version }}
    steps:
      - name: Validate version input
        if: ${{ inputs.version_number_override != '' }}
        uses: bitwarden/gh-actions/version-check@main
        with:
          version: ${{ inputs.version_number_override }}

      - name: Checkout Branch
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          ref: main

      - name: Login to Azure - CI Subscription
        uses: Azure/login@e15b166166a8746d1a47596803bd8c1b595455cf # v1.6.0
        with:
          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@main
        with:
          keyvault: "bitwarden-ci"
          secrets: "vgrassia-test-sm"
      
      - name: Get Secrets
        uses: bitwarden/sm-action@92d1d6a4f26a89a8191c83ab531a53544578f182 # v2.0.0
        with:
          access_token: ${{ steps.retrieve-secrets.outputs.vgrassia-test-sm }}
          base_url: https://vault.qa.bitwarden.pw
          secrets: |
            c8f4cc39-a958-4fbc-911f-b15d0147f3ca > GITHUB_GPG_PRIVATE_KEY
            2bd2963c-dafb-4f5a-8e3e-b15d01483506 > GITHUB_GPG_PRIVATE_KEY_PASSPHRASE

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4 # v6.1.0
        with:
          gpg_private_key: ${{ env.GITHUB_GPG_PRIVATE_KEY }}
          passphrase: ${{ env.GITHUB_GPG_PRIVATE_KEY_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Setup git
        run: |
          git config --local user.email "106330231+bitwarden-devops-bot@users.noreply.github.com"
          git config --local user.name "bitwarden-devops-bot"

      - name: Create Version Branch
        id: create-branch
        run: |
          NAME=version_bump_${{ github.ref_name }}_$(date +"%Y-%m-%d")
          git switch -c $NAME
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils

      - name: Get current version
        id: current-version
        run: |
          CURRENT_VERSION=$(xmllint --xpath '
            string(/manifest/@*[local-name()="versionName"
              and namespace-uri()="http://schemas.android.com/apk/res/android"])
            ' src/App/Platforms/Android/AndroidManifest.xml)
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Verify input version
        if: ${{ inputs.version_number_override != '' }}
        env:
          CURRENT_VERSION: ${{ steps.current-version.outputs.version }}
          NEW_VERSION: ${{ inputs.version_number_override }}
        run: |
          # Error if version has not changed.
          if [[ "$NEW_VERSION" == "$CURRENT_VERSION" ]]; then
            echo "Version has not changed."
            exit 1
          fi

          # Check if version is newer.
          printf '%s\n' "${CURRENT_VERSION}" "${NEW_VERSION}" | sort -C -V
          if [ $? -eq 0 ]; then
            echo "Version check successful."
          else
            echo "Version check failed."
            exit 1
          fi

      - name: Calculate next release version
        if: ${{ inputs.version_number_override == '' }}
        id: calculate-next-version
        uses: bitwarden/gh-actions/version-next@main
        with:
          version: ${{ steps.current-version.outputs.version }}

      - name: Bump Version - Android XML - Version Override
        if: ${{ inputs.version_number_override != '' }}
        id: bump-version-override
        uses: bitwarden/gh-actions/version-bump@main
        with:
          file_path: "src/App/Platforms/Android/AndroidManifest.xml"
          version: ${{ inputs.version_number_override }}

      - name: Bump Version - Android XML - Automatic Calculation
        if: ${{ inputs.version_number_override == '' }}
        id: bump-version-automatic
        uses: bitwarden/gh-actions/version-bump@main
        with:
          file_path: "src/App/Platforms/Android/AndroidManifest.xml"
          version: ${{ steps.calculate-next-version.outputs.version }}

      - name: Bump Version - iOS.Autofill - Version Override
        if: ${{ inputs.version_number_override != '' }}
        uses: bitwarden/gh-actions/version-bump@main
        with:
          file_path: "src/iOS.Autofill/Info.plist"
          version: ${{ inputs.version_number_override }}

      - name: Bump Version - iOS.Autofill - Automatic Calculation
        if: ${{ inputs.version_number_override == '' }}
        uses: bitwarden/gh-actions/version-bump@main
        with:
          file_path: "src/iOS.Autofill/Info.plist"
          version: ${{ steps.calculate-next-version.outputs.version }}

      - name: Bump Version - iOS.Extension - Version Override
        if: ${{ inputs.version_number_override != '' }}
        uses: bitwarden/gh-actions/version-bump@main
        with:
          file_path: "src/iOS.Extension/Info.plist"
          version: ${{ inputs.version_number_override }}

      - name: Bump Version - iOS.Extension - Automatic Calculation
        if: ${{ inputs.version_number_override == '' }}
        uses: bitwarden/gh-actions/version-bump@main
        with:
          file_path: "src/iOS.Extension/Info.plist"
          version: ${{ steps.calculate-next-version.outputs.version }}

      - name: Bump Version - iOS.ShareExtension - Version Override
        if: ${{ inputs.version_number_override != '' }}
        uses: bitwarden/gh-actions/version-bump@main
        with:
          file_path: "src/iOS.ShareExtension/Info.plist"
          version: ${{ inputs.version_number_override }}

      - name: Bump Version - iOS.ShareExtension - Automatic Calculation
        if: ${{ inputs.version_number_override == '' }}
        uses: bitwarden/gh-actions/version-bump@main
        with:
          file_path: "src/iOS.ShareExtension/Info.plist"
          version: ${{ steps.calculate-next-version.outputs.version }}

      - name: Bump Version - iOS - Version Override
        if: ${{ inputs.version_number_override != '' }}
        uses: bitwarden/gh-actions/version-bump@main
        with:
          file_path: "src/App/Platforms/iOS/Info.plist"
          version: ${{ inputs.version_number_override }}

      - name: Bump Version - iOS - Automatic Calculation
        if: ${{ inputs.version_number_override == '' }}
        uses: bitwarden/gh-actions/version-bump@main
        with:
          file_path: "src/App/Platforms/iOS/Info.plist"
          version: ${{ steps.calculate-next-version.outputs.version }}

      - name: Set Job output
        id: set-final-version-output
        run: |
          if [[ "${{ steps.bump-version-override.outcome }}" == "success" ]]; then
            echo "version=${{ inputs.version_number_override }}" >> $GITHUB_OUTPUT
          elif [[ "${{ steps.bump-version-automatic.outcome }}" == "success" ]]; then
            echo "version=${{ steps.calculate-next-version.outputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Check if version changed
        id: version-changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes_to_commit=TRUE" >> $GITHUB_OUTPUT
          else
            echo "changes_to_commit=FALSE" >> $GITHUB_OUTPUT
            echo "No changes to commit!";
          fi

      - name: Commit files
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        run: git commit -m "Bumped version to ${{ steps.set-final-version-output.outputs.version }}" -a

      - name: Push changes
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        env:
          PR_BRANCH: ${{ steps.create-branch.outputs.name }}
        run: git push -u origin $PR_BRANCH
